Connectivity fixes
dask/dask-kubernetes pull request #588
Opened 2022-10-26 18:44 UTC by baswelsh

This fixes #566 and #579.  

I also thread the `port_forward_cluster_ip` KubeCluster argument through to `get_external_address_for_scheduler_service` in order to match the behavior more closely to what I believe the intention is in the [docs](https://kubernetes.dask.org/en/latest/operator_kubecluster.html#dask_kubernetes.operator.KubeCluster).  If my interpretation or implementation here is incorrect, I am happy to correct it. I found it to be important for fast connectivity to remote clusters.  Before, we needed to wait for it to timeout (10s) before port forwarding the service and connecting remotely.

2022-10-26 19:51 UTC, baswelsh commented
@jacobtomlinson I believe I inherited this tests in a failing state - do you agree?  If so, this is ready for review!

2022-10-27 11:15 UTC, jacobtomlinson requested changes
Really excited to see this, appreciate the effort here @baswelsh. I think this captures the intent much better now.

I've left a couple of code/GitHub hygiene comments but other than that I'm happy for this to go!

The Helm CI failures are unrelated, I've opened #589 to track those separately.

2022-10-27 14:56 UTC, baswelsh commented on dask_kubernetes/common/networking.py
> +    return f"tcp://{host}:{port}"
No problem - I'll update that now

2022-10-27 15:04 UTC, baswelsh commented on dask_kubernetes/operator/kubecluster/kubecluster.py
> +    asyncio.run(_reap_clusters())
#591 - I'll undraft once the CI tasks finish green

2022-10-28 09:04 UTC, merged