KubeCluster.shutdown_on_close should be False when created from_name
dask/dask-kubernetes pull request #727
Opened 2023-05-30 15:21 UTC by Matt711

Closes #725 .

2023-06-05 13:25 UTC, jacobtomlinson reviewed
Thanks for raising this. I wonder if we can somehow allow folks to specify these options if they really want to.

For example with this change a user wouldn't be able to do the following

```python
cluster = KubeCluster.from_name("foo", shutdown_on_close=True)
```

2023-06-05 13:25 UTC, jacobtomlinson commented on dask_kubernetes/operator/kubecluster/kubecluster.py
> +        )
_Pseudo code and probably wont pass linting. But we could use the dict pipe merge now that 3.9 is our minimum!_

```suggestion
        defaults = {"create_mode": CreateMode.CONNECT_ONLY, "shutdown_on_close": False}
        kwargs = defaults | kwargs
        return cls(
            name=name,
            **kwargs,
        )
```

2023-06-05 13:25 UTC, jacobtomlinson reviewed
Thanks for raising this. I wonder if we can somehow allow folks to specify these options if they really want to.

For example with this change a user wouldn't be able to do the following

```python
cluster = KubeCluster.from_name("foo", shutdown_on_close=True)
```

2023-06-12 09:30 UTC, jacobtomlinson reviewed
Looks like CI is passing here. Could I ask you to add/update a test to cover this functionality?

2023-06-12 16:13 UTC, jacobtomlinson requested changes
Awesome thanks!

The first `kr8s` PR has landed with #721 so we can start using it 🎉.

I made some quick suggestions here that you should be able to use to swap them out.

2023-06-12 16:13 UTC, jacobtomlinson commented on dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
> +from dask_kubernetes.aiopykube import HTTPClient, KubeConfig
```suggestion
from dask_kubernetes.operator.objects import DaskCluster
```

2023-06-12 16:13 UTC, jacobtomlinson commented on dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
> +            )
```suggestion
            cluster = await DaskCluster.get("abc", namespace=ns)
```

2023-06-12 16:13 UTC, jacobtomlinson commented on dask_kubernetes/operator/kubecluster/tests/test_kubecluster.py
> +            assert cluster.obj["status"]["phase"] == "Running"
```suggestion
            assert cluster.status["phase"] == "Running"
```

2023-06-12 16:39 UTC, Matt711 commented
> Awesome thanks!
> 
> The first `kr8s` PR has landed with #721 so we can start using it 🎉.
> 
> I made some quick suggestions here that you should be able to use to swap them out.

Sweet! thanks

2023-06-13 09:38 UTC, jacobtomlinson approved these changes

2023-06-13 09:38 UTC, merged